services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://volVo:EPAM@db:5432/personal_card_db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: personal_card_db
      POSTGRES_USER: volVo
      POSTGRES_PASSWORD: EPAM
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

