# Generated by Django 5.2a1 on 2025-02-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('vaccinated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
            ],
            options={
                'unique_together': {('name', 'middle_name', 'last_name', 'age')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('vaccination_date', models.DateField()),
                ('vaccination_name', models.CharField(max_length=100)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='personal_card.personalcard')),
            ],
        ),
    ]
