# Generated by Django 5.2a1 on 2025-02-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalcard',
            unique_together=set(),
        ),
    ]
