# Generated by Django 5.2a1 on 2025-02-16 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_card', '0002_alter_personalcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcard',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
